version: '3.8'

services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: your_database
            POSTGRES_USER: your_username
            POSTGRES_PASSWORD: your_password
        ports:
            - "5432:5432"
        volumes:
            - ~/data/dd_demo_app_db/data:/usr/share/dd_demo_app_db/data
            - ~/data/dd_demo_app_db/snapshots:/usr/share/dd_demo_app_db/snapshots
            - ~/data/dd_demo_app_db/logs:/var/log/dd_demo_app_db
