services:
    postgres:
        image: postgres:14
        container_name: postgres-db
        restart: always
        environment:
            POSTGRES_DB: dd_demo_app_db
            POSTGRES_USER: dd_demo_app_db
            POSTGRES_PASSWORD: dd_demo_app_db
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
        driver: local
