spring:
  application:
    name: dd-demo-app
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none

springdoc:
  api-docs:
    path: /api-docs

management:
  datadog:
    metrics:
      export:
        enabled: ${DATADOG_ENABLED:false}
        api-key: ${DATADOG_API_KEY}
        uri: https://us5.datadoghq.com
  endpoints:
    web:
      exposure:
        include: health, metrics
  metrics:
    tags:
      application: ${spring.application.name}
      env: ${ENV:dev}
      service: ${spring.application.name}
      version: ${VERSION:0.0.1}

logging:
  structured:
    format:
      file: ecs
      console: ecs
  file:
    name: /var/log/dd-demo-app.log
  level:
    root: INFO

