spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none

springdoc:
  api-docs:
    path: /api-docs

management:
  datadog:
    metrics:
      export:
        enabled: ${DATADOG_ENABLED:false}
        api-key: ${DATADOG_API_KEY:datadog_api_key}

