spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dd_demo_app_db
    username: dd_demo_app_db
    password: dd_demo_app_db
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/dd_demo_app_db
    user: dd_demo_app_db
    password: dd_demo_app_db
    locations: classpath:db/migration


management:
  datadog:
    metrics:
      export:
        enabled: false