INSERT INTO category (name, description)
VALUES ('BAG', 'Various types of bags: backpacks, shoulder bags, clutches.'),
       ('GLASSES', 'Sunglasses and corrective glasses.'),
       ('BELT', 'Leather and textile belts of various sizes.'),
       ('SCARF', 'Scarves for any season and style.'),
       ('HAT', 'Hats and caps for different seasons.');

INSERT INTO accessory (name, description, price, discount, category_id)
VALUES ('City Backpack', 'A backpack for everyday use, city style.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'BAG')),
       ('Shoulder Bag', 'A stylish shoulder bag for everyday use.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'BAG')),
       ('Evening Clutch', 'An elegant clutch for parties and events.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'BAG')),
       ('Travel Backpack', 'A backpack for traveling and hiking.',
           ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'BAG')),
       ('Waist Bag', 'A small waist bag for carrying essentials.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'BAG')),
       ('Beach Tote', 'A large beach bag for seaside relaxation.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'BAG')),
       ('Shopper Bag', 'A convenient bag for shopping.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'BAG')),
       ('Laptop Bag', 'A bag with a compartment for a laptop up to 15 inches.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'BAG')),
       ('Gym Backpack', 'A backpack for gym and sports.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'BAG')),
       ('Crossbody Bag', 'A compact bag with a long strap.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'BAG')),
       ('Aviator Sunglasses', 'Aviator-style sunglasses.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'GLASSES')),
       ('Corrective Glasses', 'Glasses with corrective lenses.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'GLASSES')),
       ('Computer Glasses', 'Glasses for protecting eyes while working on a computer.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'GLASSES')),
       ('Polarized Sunglasses', 'Sunglasses with polarized lenses.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'GLASSES')),
       ('Sport Sunglasses', 'Glasses for active sports and recreation.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'GLASSES')),
       ('Square Sunglasses', 'Sunglasses with a square shape.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'GLASSES')),
       ('Round Sunglasses', 'Trendy round sunglasses.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'GLASSES')),
       ('Rimless Glasses', 'Lightweight rimless glasses.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'GLASSES')),
       ('Cat Eye Sunglasses', 'Cat-eye shaped sunglasses.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'GLASSES')),
       ('Mirrored Sunglasses', 'Sunglasses with mirrored lenses.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'GLASSES')),
       ('Leather Belt', 'Classic leather belt.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'BELT')),
       ('Textile Belt', 'Durable textile belt for jeans.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'BELT')),
       ('Automatic Buckle Belt', 'Belt with an automatic buckle for easy adjustment.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'BELT')),
       ('Braided Belt', 'Braided belt for a casual look.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'BELT')),
       ('Decorative Belt', 'Belt with metal decorative elements.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'BELT')),
       ('Teen Belt', 'Trendy belt for teenagers.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'BELT')),
       ('Sport Belt', 'Wide belt for active wear.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'BELT')),
       ('Office Belt', 'Classic belt for office style.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'BELT')),
       ('Chain Belt', 'Belt with chain elements.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'BELT')),
       ('Dress Belt', 'Thin belt for highlighting the waist.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'BELT')),
       ('Wool Scarf', 'Warm wool scarf for winter.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'SCARF')),
       ('Cashmere Scarf', 'Luxurious cashmere scarf.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'SCARF')),
       ('Silk Scarf', 'Light silk scarf for spring.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'SCARF')),
       ('Plaid Scarf', 'Large plaid scarf for cozy evenings.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'SCARF')),
       ('Snood Scarf', 'Ring-shaped scarf that is easy to wear.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'SCARF')),
       ('Hooded Scarf', 'Convenient hooded scarf for wind protection.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'SCARF')),
       ('Lightweight Scarf', 'Light summer scarf made of cotton.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'SCARF')),
       ('Printed Scarf', 'Scarf with a bright print.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'SCARF')),
       ('Knitted Scarf', 'Handmade knitted scarf.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'SCARF')),
       ('Sports Scarf', 'Light scarf for active recreation.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'SCARF')),
       ('Felt Hat', 'Stylish felt hat for autumn.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'HAT')),
       ('Panama Hat', 'Light panama hat for sun protection.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'HAT')),
       ('Wide-Brimmed Hat', 'Hat with wide brims for sun protection.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'HAT')),
       ('Straw Hat', 'Light straw hat.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'HAT')),
       ('Classic Hat', 'Classic hat for a stylish look.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'HAT')),
       ('Jazz Hat', 'Trendy jazz-style hat.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'HAT')),
       ('Sports Cap', 'Cap for active recreation.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'HAT')),
       ('Hat with Ears', 'Hat with decorative ears.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'HAT')),
       ('Travel Hat', 'Hat for travel and expeditions.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'HAT')),
       ('Beach Hat', 'Hat with wide brims for the beach.',
        ROUND((RANDOM() * (200 - 20) + 20)::NUMERIC, 2), ROUND((RANDOM() * 15)::NUMERIC, 2),
        (SELECT id FROM category WHERE name = 'HAT'));

INSERT INTO accessory_attribute (type, value, accessory_id)
VALUES ('MATERIAL', 'Polyester', (SELECT id FROM accessory WHERE name = 'City Backpack')),
       ('COLOR', 'Black', (SELECT id FROM accessory WHERE name = 'City Backpack')),
       ('SIZE', 'L', (SELECT id FROM accessory WHERE name = 'City Backpack')),

       ('MATERIAL', 'Leather', (SELECT id FROM accessory WHERE name = 'Shoulder Bag')),
       ('COLOR', 'Brown', (SELECT id FROM accessory WHERE name = 'Shoulder Bag')),
       ('SIZE', 'M', (SELECT id FROM accessory WHERE name = 'Shoulder Bag')),

       ('MATERIAL', 'Leather', (SELECT id FROM accessory WHERE name = 'Evening Clutch')),
       ('COLOR', 'Red', (SELECT id FROM accessory WHERE name = 'Evening Clutch')),
       ('SIZE', 'S', (SELECT id FROM accessory WHERE name = 'Evening Clutch')),

       ('MATERIAL', 'Nylon', (SELECT id FROM accessory WHERE name = 'Travel Backpack')),
       ('COLOR', 'Green', (SELECT id FROM accessory WHERE name = 'Travel Backpack')),
       ('SIZE', 'XL', (SELECT id FROM accessory WHERE name = 'Travel Backpack')),

       ('MATERIAL', 'Textile', (SELECT id FROM accessory WHERE name = 'Waist Bag')),
       ('COLOR', 'Blue', (SELECT id FROM accessory WHERE name = 'Waist Bag')),
       ('SIZE', 'S', (SELECT id FROM accessory WHERE name = 'Waist Bag')),

       ('MATERIAL', 'Cotton', (SELECT id FROM accessory WHERE name = 'Beach Tote')),
       ('COLOR', 'Yellow', (SELECT id FROM accessory WHERE name = 'Beach Tote')),
       ('SIZE', 'L', (SELECT id FROM accessory WHERE name = 'Beach Tote'));

INSERT INTO inventory (accessory_id, quantity)
VALUES ((SELECT id FROM accessory WHERE name = 'City Backpack'), 100),
       ((SELECT id FROM accessory WHERE name = 'Shoulder Bag'), 50),
       ((SELECT id FROM accessory WHERE name = 'Evening Clutch'), 30),
       ((SELECT id FROM accessory WHERE name = 'Travel Backpack'), 20),
       ((SELECT id FROM accessory WHERE name = 'Waist Bag'), 80),
       ((SELECT id FROM accessory WHERE name = 'Beach Tote'), 60);
